using LargeIntestine;
using SplineMesh;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

[RequireComponent(typeof(Spline))]
public class EndoscopeSpline : MonoBehaviour
{
    public static EndoscopeSpline sharedInstance;
    private bool toUpdate = false;
    private GameObject generated;
    public GameObject Generated
    {
        get
        {
            if (generated == null)
            {
                string generatedName = "generated by " + GetType().Name;
                var generatedTranform = transform.Find(generatedName);
                generated = generatedTranform != null ? generatedTranform.gameObject : UOUtility.Create(generatedName, gameObject);
            }
            return generated;
        }
    }

    [SerializeField]
    public List<GameObject> wayPoints = new List<GameObject>();
    public GameObject tubeSectionPrefab;
    public GameObject cameraSectionPrefab;
    public GameObject cameraPrefab;
    public int tubeSegmentCount;
    public int cameraSegmentCount;
    public float segmentSpacing;
    [Header("Deformer variables")]
    public float force = 10f;
    public float forceOffset = 0.1f;

    private bool mReady = false;
    private Spline spline;
    private Joint rootJoint;
    private Endoscope endoscope;
    private float localSpacing;
    private bool updateNodes;
    private bool initialized = false;
    public List<Transform> dmcInputs;
    private List<MeshRenderer> renderers;

    private void Awake()
    {
        if (sharedInstance == null)
        {
            sharedInstance = this;
        }
        else
        {
            Destroy(gameObject);
        }
    }

    public void ControlledStart()
    {
        toUpdate = true;
        spline = GetComponent<Spline>();
        //IntestineSpline.sharedInstance.ControlledStart();
        endoscope = Endoscope.sharedInstance;
        dmcInputs = new List<Transform>();
        //LI_ProceduralGenerator.sharedInstance.CreateLGIEModel();
    }

    private void Update()
    {

        if (toUpdate)
        {
            toUpdate = false;
            Generate();
            UpdateSpline();
            mReady = true;
            //Debug.LogWarning("mReady");
        }
        /*if(mReady) {
            mReady = false;
            LI_ProceduralGenerator.sharedInstance.CreateLGIEModel();
        }*/
        //no hay rendereres
        /*renderers = Generated.transform.parent.GetComponentsInChildren<MeshRenderer>(true).ToList();
        if(renderers.Count != 0)
        {
            renderers.ForEach(mr =>
            {
                if (mr.isVisible)
                {
                    Debug.Log("es visible");
                    updateNodes = true;
                    mr.enabled = true;
                }
                else
                {
                    mr.enabled = false;
                }

            });
        }*/

        //if (updateNodes)
        //{
        UpdateNodes();
        //}



        //TODO investigar si esto es posible en un late update o algo
        /*if (!initialized)
        {
            initialized = !initialized;
            endoscope.ControlledStart();
        }*/
    }

    private void UpdateNodes()
    {
        int i = 0;
        updateNodes = false;
        foreach (GameObject wayPoint in wayPoints)
        {
            //LUGILDE -> a�ado la distancia de los vectores up para ver si ha rotado
            var node = spline.nodes[i++];
            if (Vector3.Distance(node.Position, transform.InverseTransformPoint(wayPoint.transform.position)) > 0.001f /*|| Vector3.Distance(node.Up, wayPoint.transform.up) > 0.001f*/)
            {
                node.Position = transform.InverseTransformPoint(wayPoint.transform.position);
                node.Up = wayPoint.transform.up;
            }
        }
    }

    private void UpdateSpline()
    {
        foreach (var node in wayPoints.ToList())
        {
            if (node == null) wayPoints.Remove(node);
        }
        int nodeCount = wayPoints.Count;
        while (spline.nodes.Count < nodeCount)
        {
            spline.AddNode(new SplineNode(Vector3.zero, Vector3.zero));
        }
        while (spline.nodes.Count > nodeCount && spline.nodes.Count > 2)
        {
            spline.RemoveNode(spline.nodes.Last());
        }
    }

    private void Generate()
    {
        UOUtility.DestroyChildren(Generated);
        wayPoints.Clear();
        localSpacing = 0;
        endoscope.cameraRBs = GenerateSegmentSections(cameraSegmentCount, cameraSectionPrefab, "Camera");
        endoscope.tubeRBs = GenerateSegmentSections(tubeSegmentCount, tubeSectionPrefab, "Tube");
        endoscope.originalRelativeCameraPosition = endoscope.cameraRBs.First().transform.InverseTransformPoint(endoscope.tubeRBs.First().transform.position);
        var camera = UOUtility.Instantiate(cameraPrefab, endoscope.cameraRBs.First().transform);
        camera.transform.localRotation = Quaternion.Euler(0f, 180f, 0f);
        endoscope.endoscopeCamera = camera.GetComponent<Camera>();
        endoscope.endoscopeLight = camera.GetComponent<Light>();
        endoscope.ControlledStart();
        UOUtility.Destroy(rootJoint);
    }


    private List<Rigidbody> GenerateSegmentSections(int sectionCount, GameObject prefab, string sectionName)
    {
        List<Rigidbody> rbList = new List<Rigidbody>();
        var cameraSegment = UOUtility.Create(sectionName + "Segment", Generated);
        //EndoscopeControllerV3.sharedInstance.CameraSegment = cameraSegment;
        for (int i = 0; i < sectionCount; i++)
        {
            var section = UOUtility.Instantiate(prefab, cameraSegment.transform);
            section.name = sectionName + "Section_" + i;
            rbList.Add(ConfigureSection(section));
        }
        return rbList;
    }

    private Rigidbody ConfigureSection(GameObject section)
    {
        section.transform.Translate(0, 0, localSpacing);
        var segRB = section.GetComponent<Rigidbody>();
        segRB.maxAngularVelocity = 10f;
        //PARA GRAVEDAD
        segRB.useGravity = false;
        if (rootJoint != null)
        {
            rootJoint.connectedBody = segRB;
        }
        rootJoint = section.GetComponent<Joint>();
        wayPoints.Add(section);
        localSpacing += segmentSpacing;
        //section.AddComponent<DMC_Input>();
        dmcInputs.Add(section.transform);
        return segRB;
    }

}