using GeometryUtils;
using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using Utility.MeshHelper;

namespace SplineMesh
{
    /// <summary>
    /// Example of component to show the deformation of the mesh on a changing
    /// interval and changing spline nodes.
    /// 
    /// In this example, as the MeshBender is working on spline space, it will update
    /// the mesh if one of the curve change. Each change make the MeshBender "dirty" and
    /// it will compute the mesh only once on it's next update call.
    /// 
    /// This component is only for demo purpose and is not intended to be used as-is.
    /// </summary>
    [ExecuteInEditMode]
    [RequireComponent(typeof(Spline))]
    public class GrowingEndoscope : MonoBehaviour
    {
        public float movementRate = 0.1f;
        private GameObject generated;
        private Spline spline;
        private float rate = 0;
        private CustomMeshBender customMeshBender;
        private Transform endoscopeCameraTransform;

        public Mesh mesh;
        public Material material;
        public Vector3 rotation;
        public Vector3 scale;
        public Camera endoscopeCamera;


        private void OnEnable()
        {
            rate = 0;
            Init();
#if UNITY_EDITOR
            EditorApplication.update += EditorUpdate;
#endif
        }

        void OnDisable()
        {
#if UNITY_EDITOR
            EditorApplication.update -= EditorUpdate;
#endif
        }

        private void OnValidate()
        {
            Init();
        }

        private void Update()
        {
            EditorUpdate();
        }

        void EditorUpdate()
        {
            if(Input.GetKey(KeyCode.W))
            {
                Debug.Log("EditorUpdate");
                rate += movementRate;
                if(rate > 1)
                {
                    rate--;
                }
                Contort();
            }
            /*rate += Time.deltaTime / DurationInSecond;
            if (rate > 1)
            {
                rate--;
            }
            Contort();*/
        }

        private void Contort()
        {
            float nodeDistance = 0;
            int i = 0;
            foreach (var n in spline.nodes)
            {
                float nodeDistanceRate = nodeDistance / spline.Length;
                n.Scale = new Vector2(1f, 1f);
            }

            if (generated != null)
            {
                customMeshBender.SetInterval(spline, 0, spline.Length * rate);
                customMeshBender.ComputeIfNeeded();
            }
            //endoscopeCameraTransform.position = spline.GetSample(rate).location;
        }

        private void Init()
        {
            endoscopeCameraTransform = endoscopeCamera.transform;
            string generatedName = "generated by " + GetType().Name;
            var generatedTranform = transform.Find(generatedName);
            generated = generatedTranform != null ? generatedTranform.gameObject : UOUtility.Create(generatedName, gameObject,
                typeof(SkinnedMeshRenderer),
                typeof(CustomMeshBender));

            generated.GetComponent<SkinnedMeshRenderer>().material = material;

            customMeshBender = generated.GetComponent<CustomMeshBender>();
            spline = GetComponent<Spline>();
 
            customMeshBender.SetInterval(spline, 0, 0.01f);

            var meshData = new MeshData(mesh,
                    Vector3.zero,
                    Quaternion.Euler(rotation),
                    scale,
                    true);
            meshData.BuildData();
            customMeshBender.MeshData = meshData;
            customMeshBender.Configure();
        }
    }
}
